// Generated by ts-to-zod
import { z } from "zod";

export const definitionsCreateUserRequestSchema = z.object({
  name: z.string(),
  age: z.number(),
  sex: z.union([z.literal("male"), z.literal("female")]),
});
